language: python

python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

install:
  - pip install pylint
  - pip install .

script:
  - pylint pi_montecarlo.py setup.py test/
  - python -m unittest
  - pi -h
